name: linter and tests check

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: make install
      - run: make test
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
      # - run: make lint
