name: linter and tests check

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install dependencies
        run: |
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run test
        run: |
          make test
      - name: Code Climate Coverage Action
        if: always()
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
